In [1]:
import numpy as np

tr=np.array([7,10,15]); 
t0=1
SEL=np.zeros((np.size(tr),np.size(tr)));

for i in range(0,np.size(tr)):
    for j in range(0,np.size(tr)):
        SEL[i,j]=(tr[i]-t0)/(tr[j]-t0)

print('Selectivity i,j\n',SEL)

Selectivity i,j
 [[1.         0.66666667 0.42857143]
 [1.5        1.         0.64285714]
 [2.33333333 1.55555556 1.        ]]


In [2]:
import numpy as np

tr=np.array([7,10,15]); 
tw=np.array([1,2,1.5]); 
L=10 #cm

N=(16*(tr/tw)**2)

H=L/N

R=np.zeros((np.size(tr),np.size(tr)));

for i in range(0,np.size(tr)):
    for j in range(0,np.size(tr)):
        R[i,j]=abs((tr[i]-tr[j])/(2*(tw[i]+tw[j])))


print('\nHeight of a theoretical plates ',H,' [-]')
print('Number of theoretical plates ',H,' cm')
print('Resolution i,j\n',R)


Height of a theoretical plates  [0.0127551 0.025     0.00625  ]  [-]
Number of theoretical plates  [0.0127551 0.025     0.00625  ]  cm
Resolution i,j
 [[0.         0.5        1.6       ]
 [0.5        0.         0.71428571]
 [1.6        0.71428571 0.        ]]
